version: '3.9'


services:
  app:
    container_name: go-app
    image: url-shortner:v1 
    build: .
    environment:
      DB_PORT: "5432"
      DB_NAME: "url_shortening"
      DB_USER_NAME: "postgres"
      DB_HOST: "go_db"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: